apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-gcp-workload-identity
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-gcp-workload-identity
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration provides a foundation to build and operate GCP Workload Idenitities.
    meta.crossplane.io/readme: |
     This configuration is used for deploying and managing GCP Workload Identity using Crossplane.

     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-gcp-workload-identity).
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-gcp-gke
      # renovate: datasource=github-releases depName=upbound/configuration-gcp-gke
      version: "v0.7.0"
